Models/ConverterViewModel.cs
using System;

namespace UnitConverter11142018.Models
{
    public class ConverterViewModel
    {

        public decimal ValueToConvert {get; set;}
        public string ConversionType {get; set;}
        public decimal ConversionValue {get ; set;}

    }
}

Models/ErrorViewModel.cs
using System;

namespace UnitConverter11142018.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ConversionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UnitConverter11142018.Models;

namespace UnitConverter11142018.Controllers
{
    public class ConversionController : Controller
    {
      
        public IActionResult Index()
            {
                return View();
            }
        [HttpGet]
        public IActionResult Converter()
            {
                
                return View();
            }
    [HttpPost]
       public IActionResult DoConversion(ConverterViewModel model)
       {
            switch (model.ConversionType) {
                case "OuncestoPounds":
                    model.ConversionValue = (model.ValueToConvert * 0.0625m);                  
                    break;

                case "OuncestoGrams":   
                    model.ConversionValue = (model.ValueToConvert / 0.035274m);
                    break;
                case "OuncestoKilograms":
                    model.ConversionValue = (model.ValueToConvert / 35.274m);
                    break;
                case "PoundstoOunces":
                    model.ConversionValue = (model.ValueToConvert * 16.00m);
                   break;
                case "PoundstoGrams":
                    model.ConversionValue = (model.ValueToConvert / 0.0022046m);
                   break;
                case "PoundstoKilograms":
                    model.ConversionValue = (model.ValueToConvert / 2.2046m);
                   break;
                case "GramstoOunces":
                    model.ConversionValue = (model.ValueToConvert / 28.3495m);
                   break;
                case "GramstoPounds":
                    model.ConversionValue = (model.ValueToConvert / 453.59237m);
                   break;
                case "GramstoKilograms":
                    model.ConversionValue = (model.ValueToConvert / 1000.0m);
                   break;
                case "KilogramstoOunces":
                    model.ConversionValue = (model.ValueToConvert / 0.02834952m);
                   break;
                case "KilogramstoPounds":
                    model.ConversionValue = (model.ValueToConvert / 0.45359237m);
                    break;
                case "KilogramstoGrams":
                    model.ConversionValue = (model.ValueToConvert * 1000.0m);
                   break;
              
                case "MeterstoFeet":
                    model.ConversionValue = (model.ValueToConvert / 0.3048m);
                   break;
                case "MeterstoYards":
                    model.ConversionValue = (model.ValueToConvert * 1.0936m);
                    break;
                case "FeettoMeters":
                    model.ConversionValue = (model.ValueToConvert * 0.3048m);
                    break;
                case "FeettoYards":
                    model.ConversionValue = (model.ValueToConvert * 0.3333m);
                    break;
                case "YardstoMeters":
                    model.ConversionValue = (model.ValueToConvert / 1.0936m);
                    break;
                case "YardstoFeet":
                    model.ConversionValue = (model.ValueToConvert * 3.0m);
                   break;
                      case "CelciusToFahrenheit":
                    model.ConversionValue = ((model.ValueToConvert * 1.8m) + 32.0m);
                    break;
                case "CelciustoKelvin":
                    model.ConversionValue = ((model.ValueToConvert + 273.15m));
                    break;
                case "FahrenheittoCelcius":
                    model.ConversionValue = ((model.ValueToConvert - 32.0m) / 1.8m);
                    break;
                case "FahrenheittoKelvin":
                    model.ConversionValue = ((model.ValueToConvert + 459.67m) * (5.0m / 9.0m));
                   break;
                case "KelvintoFahrenheit":
                    model.ConversionValue = ((model.ValueToConvert * 1.8m) -459.67m);
                    break;
                case "KelvintoCelcius":
                    model.ConversionValue = (model.ValueToConvert - 273.15m);
                    break;
                  default:
                  break;
                

            }
            return View(model);
            
       }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UnitConverter11142018.Models;

namespace UnitConverter11142018.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Conversion/Converter.cshtml
@model ConverterViewModel 

<form asp-controller="Conversion" asp-action="DoConversion" method="POST">
  <!-- borrowed some of this from: https://www.w3schools.com/html/html_forms.asp -->
  
  Value to Convert:<br>
  <input type="text" asp-for="@Model.ValueToConvert">
  <br>
  Conversion Type:<br>
   <select type="text" asp-for="@Model.ConversionType">
       <!--Mass-->
        <option value="OuncestoPounds"> Ounces to Pounds</option>
        <option value="OuncestoGrams"> Ounces to Grams</option>
        <option value="OuncestoKilograms"> Ounces to Kilograms</option>
        <option value="PoundstoOunces"> Pounds to Ounces</option>
        <option value="PoundstoGrams"> Pounds to Grams</option>
        <option value="PoundstoKilograms"> Pounds to Kilograms</option>
        <option value="GramstoOunces"> Grams to Ounces</option>
        <option value="GramstoPounds"> Grams to Pounds</option>
        <option value="GramstoKilograms"> Grams to Kilograms</option>
        <option value="KilogramstoOunces"> Kilograms to Ounces</option>
        <option value="KilogramstoPounds"> Kilograms to Pounds</option>
        <option value="KilogramstoGrams"> Kilograms to Grams</option>
       <!--Length-->        
        <option value="MeterstoFeet"> Meters to Feet</option>
        <option value="MeterstoYards"> Meters to Yards</option>
        <option value="FeettoMeters"> Feet to Meters</option>
        <option value="FeettoYards"> Feet to Yards</option>
        <option value="YardstoFeet"> Yards to Feet</option>
        <option value="YardstoMeters"> Yards to Meters</option>
       <!--Temp-->
        <option value="CelciusToFahrenheit"> Celcius to Fahrenheit</option>
        <option value="CelciustoKelvin"> Celcius to Kelvin</option>
        <option value="FahrenheittoCelcius"> Fahrenheit to Celcius</option>
        <option value="FahrenheittoCelcius"> Fahrenheit to Kelvin</option>
        <option value="KelvintoFahrenheit"> Kelvin to Fahrenheit</option>
        <option value="KelvintoCelcius"> Kelvin to Celcius</option>
    </select>

    <br>  
    <br>

<input type="submit" value="Convert"> 
</form>

Views/Conversion/DoConversion.cshtml
@model ConverterViewModel

<h1>Results</h1>

<p>
    @Model.ValueToConvert <br/>
    @Model.ConversionType <br/>
    @Model.ConversionValue <br/>
</p>

Views/Conversion/Index.cshtml
<h1>The message is</h1>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UnitConverter11142018</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UnitConverter11142018</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Page1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Page2</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2018 - UnitConverter11142018 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>